import jsPDF from 'jspdf'
import 'jspdf-autotable'
import { formatDate } from './formatters'

export const generateCaseReport = (caseData, evidenceList) => {
    const doc = new jsPDF()

    // --- Header ---
    doc.setFontSize(22)
    doc.setFont('helvetica', 'bold')
    doc.text('Case Report', 14, 20)

    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.text(`Generated on: ${new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}`, 14, 28)

    // --- Line Separator ---
    doc.setLineWidth(0.5)
    doc.line(14, 32, 196, 32)

    // --- Case Details ---
    let y = 45
    doc.setFontSize(16)
    doc.setFont('helvetica', 'bold')
    doc.text('Case Summary', 14, y)

    y += 10
    doc.setFontSize(11)
    doc.setFont('helvetica', 'normal')

    const details = [
        ['Case Number:', caseData.case_number],
        ['Title:', caseData.title],
        ['Status:', caseData.status.toUpperCase()],
        ['Created Date:', formatDate(caseData.created_at)],
        ['Description:', caseData.description || 'N/A'],
    ]

    details.forEach(([label, value]) => {
        doc.setFont('helvetica', 'bold')
        doc.text(label, 14, y)
        doc.setFont('helvetica', 'normal')

        // Handle multi-line description
        if (label === 'Description:') {
            const splitDesc = doc.splitTextToSize(value, 150)
            doc.text(splitDesc, 50, y)
            y += (splitDesc.length * 5) + 2
        } else {
            doc.text(String(value), 50, y)
            y += 7
        }
    })

    // --- Evidence Table ---
    y += 10
    doc.setFontSize(16)
    doc.setFont('helvetica', 'bold')
    doc.text('Evidence Inventory', 14, y)

    const tableColumn = ["File Name", "Type", "Status", "Integrity", "Hash (SHA-256)"]
    const tableRows = []

    evidenceList.forEach(evidence => {
        const evidenceData = [
            evidence.file_name,
            evidence.file_type || evidence.category || 'N/A',
            evidence.status.toUpperCase(),
            evidence.integrity_status.toUpperCase(),
            evidence.original_hash || 'N/A',
        ]
        tableRows.push(evidenceData)
    })

    doc.autoTable({
        top: y + 5,
        head: [tableColumn],
        body: tableRows,
        startY: y + 5,
        theme: 'striped',
        headStyles: { fillColor: [59, 130, 246] }, // Blue header
        styles: { fontSize: 8, cellPadding: 2 },
        columnStyles: {
            4: { cellWidth: 60 } // Limit Hash column width
        }
    })

    // --- Footer ---
    const pageCount = doc.internal.getNumberOfPages()
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i)
        doc.setFontSize(8)
        doc.text('Confidential - Generated by DCoC System', 14, 285)
        doc.text(`Page ${i} of ${pageCount}`, 190, 285, { align: 'right' })
    }

    // --- Save ---
    doc.save(`Complete_Case_Report_${caseData.case_number}.pdf`)
}
